TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------------------
# In a Diamond Support Module, install
# templates like this
#
DB += bo.template
DB += bi.template
DB += ao.template
DB += ai.template
DB += stringin.template
DB += mbboDirect.template
DB += mbbiDirect.template
DB += plcInfo.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

