TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------------------
# In a Diamond Support Module, install
# templates like this
#
DB += ether_ip_bo.template
DB += ether_ip_bi.template
DB += ether_ip_ao.template
DB += ether_ip_ai.template
DB += ether_ip_stringin.template
DB += ether_ip_mbboDirect.template
DB += ether_ip_mbbiDirect.template
DB += ether_ip_plcInfo.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

